---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: how bluexp operational resiliency works, what is operational resiliency, bluexp 
summary: BlueXPの運用の耐障害性は、アラートとイベントを分析して、サービスとソリューションの健全性、アップタイム、パフォーマンスを維持するのに役立つサービスです。運用の耐障害性サービスとIT運用の自動修復の提案を使用すると、システム停止や障害が発生する前に推奨される修正策を実装できます。 
---
= BlueXPの運用耐障害性について説明します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
BlueXPの運用の耐障害性は、アラートとイベントを分析してサービスとソリューションの健全性、アップタイム、パフォーマンスを維持するのに役立つサービスです。運用の耐障害性サービスとIT運用リスクの自動修正提案を使用すると、システム停止や障害が発生する前に推奨される修正策を実装できます。

このBlueXP  サービスでは、Active IQデジタルアドバイザ（デジタルアドバイザ）のガイダンスに基づいて、NetApp ONTAPクラスタへの修正措置を実施します。このサービスは、ファームウェアやソフトウェアの設定の問題など、セキュリティの脆弱性を検出します。



== BlueXPの運用耐障害性を利用するメリット

BlueXPの運用耐障害性には、次のようなメリットがあります。

* クラスタでの修正手順の自動化
* ダッシュボードの[Summary]ビューには、各リスクの修正の状態が表示されます
* 実行されたさまざまなアクションを追跡できるログ




== BlueXPの優れた運用耐障害性

運用の耐障害性サービスを使用すると、次の目標を達成できます。

* 自動化されたワークフローにより、ストレージ環境に影響を及ぼすリスクを検出し、リスクを軽減するための措置を講じることができます。
* セキュリティの脆弱性に関連する問題など、運用上の推奨事項を確認して対処します。




== コスト

ネットアップは、このサービスの利用に対して料金を請求することはありません。



== サポートされている環境

BlueXPの運用耐障害性機能は、オンプレミスのNetApp ONTAP クラスタを分析します。
