---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: how bluexp operational resiliency works, what is operational resiliency, bluexp 
summary: 運用の耐障害性は、アラートとイベントを分析してサービスとソリューションの健全性、アップタイム、パフォーマンスを維持するのに役立つサービスです。運用の耐障害性サービスとIT運用の自動修復の提案を使用すると、システム停止や障害が発生する前に推奨される修正策を実装できます。 
---
= 運用の耐障害性サービスについて説明します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
運用の耐障害性とは、アラートとイベントを分析してサービスとソリューションの健全性、アップタイム、パフォーマンスを維持するのに役立つサービスです。運用の耐障害性サービスとIT運用リスクの自動修正提案を使用すると、システム停止や障害が発生する前に推奨される修正策を実装できます。

このBlueXPサービスでは、NetApp Digital Advisor（旧Active IQ ）のガイダンスに基づいて、NetApp ONTAP クラスタへの修正措置を実施します。このサービスは、ファームウェアやソフトウェアの設定の問題など、セキュリティの脆弱性を検出します。



== 運用の耐障害性サービスを使用するメリット

運用の耐障害性サービスには、次のようなメリットがあります。

* クラスタでの修正手順の自動化
* ダッシュボードの[Summary]ビューには、各リスクの修正の状態が表示されます
* 実行されたさまざまなアクションを追跡できるログ




== 運用の耐障害性サービスでできること

運用の耐障害性サービスを使用すると、次の目標を達成できます。

* 自動化されたワークフローにより、ストレージ環境に影響を及ぼすリスクを検出し、リスクを軽減するための措置を講じることができます。
* セキュリティの脆弱性に関連する問題など、運用上の推奨事項を確認して対処します。




== コスト

ネットアップは、このサービスの利用に対して料金を請求することはありません。



== サポートされている環境

運用の耐障害性サービスは、オンプレミスのNetApp ONTAP クラスタを分析します。
